server:
  port: 8761

#security
security:
  basic:
    enabled: true   #开启给予http basic认证
  user:
    name: burton     #配置登录账号
    password: burton #配置登录密码

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://burton1:burton1@localhost1:8762/eureka/,http://burton2:burton2@localhost2:8763/eureka/
  instance:
    hostname: localhost
  server:
    enable-self-preservation: true

