server:
  port: 8763

#security
security:
  basic:
    enabled: true   #开启给予http basic认证
  user:
    name: burton2     #配置登录账号
    password: burton2 #配置登录密码

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://burton:burton@localhost:8761/eureka/,http://burton1:burton1@localhost1:8762/eureka/
  instance:
    hostname: localhost2
  server:
    enable-self-preservation: true
